export const allMovies = [
  { trackName: "Pushpa: The Rise", artworkUrl100: "https://image.tmdb.org/t/p/w500/4DpNRjV7ITZ1GzCvrvCk86th0w.jpg", primaryGenreName: "Action" },
  { trackName: "RRR", artworkUrl100: "https://image.tmdb.org/t/p/w500/u0XUBNQWlOvrh0Gd97ARGpIkL0.jpg", primaryGenreName: "Action" },
  { trackName: "K.G.F: Chapter 2", artworkUrl100: "https://image.tmdb.org/t/p/w500/khNVygolU0TxLIDWff5tQlAhZ23.jpg", primaryGenreName: "Action" },
  { trackName: "Jawan", artworkUrl100: "https://image.tmdb.org/t/p/w500/jFt1gS4BGHlK8xt76Y81Alp4dbt.jpg", primaryGenreName: "Action" },
  { trackName: "Pathaan", artworkUrl100: "https://image.tmdb.org/t/p/w500/arf00BkwvXo0CFKbaD9OpqdE4Nu.jpg", primaryGenreName: "Action" },
  { trackName: "Baahubali 2: The Conclusion", artworkUrl100: "https://image.tmdb.org/t/p/w500/21sC2assImQIYCEDA84Qh9d1RsK.jpg", primaryGenreName: "Action" },
  { trackName: "Kalki 2898 AD", artworkUrl100: "https://image.tmdb.org/t/p/w500/rstcAnBeCkxNQjNp3YXrF6IP1tW.jpg", primaryGenreName: "Sci-Fi" },
  { trackName: "Obsession", artworkUrl100: "https://image.tmdb.org/t/p/w500/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg", primaryGenreName: "Movie" },
  { trackName: "Toy Story 5", artworkUrl100: "https://image.tmdb.org/t/p/w500/sfQtVlIHljToOwYjhe21KPGzZWK.jpg", primaryGenreName: "Movie" },
  { trackName: "Moana", artworkUrl100: "https://image.tmdb.org/t/p/w500/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg", primaryGenreName: "Movie" },
  { trackName: "Disclosure Day", artworkUrl100: "https://image.tmdb.org/t/p/w500/AnJ8IQJI23hNpYXVNaythu061Ru.jpg", primaryGenreName: "Movie" },
  { trackName: "Scary Movie", artworkUrl100: "https://image.tmdb.org/t/p/w500/1KlYdWoOrbL5ux357rW9LC155qw.jpg", primaryGenreName: "Movie" },
  { trackName: "Backrooms", artworkUrl100: "https://image.tmdb.org/t/p/w500/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg", primaryGenreName: "Movie" },
  { trackName: "Passenger", artworkUrl100: "https://image.tmdb.org/t/p/w500/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg", primaryGenreName: "Movie" },
  { trackName: "The Furious", artworkUrl100: "https://image.tmdb.org/t/p/w500/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg", primaryGenreName: "Movie" },
  { trackName: "The Devil Wears Prada 2", artworkUrl100: "https://image.tmdb.org/t/p/w500/fCAURTUx3YfsJ8k9I0UamjSILiR.jpg", primaryGenreName: "Movie" },
  { trackName: "Your Heart Will Be Broken", artworkUrl100: "https://image.tmdb.org/t/p/w500/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg", primaryGenreName: "Movie" },
  { trackName: "The Odyssey", artworkUrl100: "https://image.tmdb.org/t/p/w500/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg", primaryGenreName: "Movie" },
  { trackName: "Citizen Vigilante", artworkUrl100: "https://image.tmdb.org/t/p/w500/6LmJD3Wohe0g4U62wgi7RyJqfE4.jpg", primaryGenreName: "Movie" },
  { trackName: "The Shawshank Redemption", artworkUrl100: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg", primaryGenreName: "Movie" },
  { trackName: "Deep Water", artworkUrl100: "https://image.tmdb.org/t/p/w500/kjcuS7xaRyqRjVaVcH4t0qHshuX.jpg", primaryGenreName: "Movie" },
  { trackName: "Michael", artworkUrl100: "https://image.tmdb.org/t/p/w500/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg", primaryGenreName: "Movie" },
  { trackName: "Project Hail Mary", artworkUrl100: "https://image.tmdb.org/t/p/w500/yihdXomYb5kTeSivtFndMy5iDmf.jpg", primaryGenreName: "Movie" },
  { trackName: "Mortal Kombat II", artworkUrl100: "https://image.tmdb.org/t/p/w500/hwRdDFIhaEmpRgoki805YvyyjZf.jpg", primaryGenreName: "Movie" },
  { trackName: "The Super Mario Galaxy Movie", artworkUrl100: "https://image.tmdb.org/t/p/w500/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg", primaryGenreName: "Movie" },
  { trackName: "Avatar: Fire and Ash", artworkUrl100: "https://image.tmdb.org/t/p/w500/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg", primaryGenreName: "Movie" },
  { trackName: "Evil Dead Burn", artworkUrl100: "https://image.tmdb.org/t/p/w500/ztadKzIIR0ERYqpHteaPFtk7inP.jpg", primaryGenreName: "Movie" },
  { trackName: "The Get Out", artworkUrl100: "https://image.tmdb.org/t/p/w500/zlkeH0s7dDxcnuPcHBqAyXFUxqN.jpg", primaryGenreName: "Movie" },
  { trackName: "Avatar Aang: The Last Airbender", artworkUrl100: "https://image.tmdb.org/t/p/w500/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg", primaryGenreName: "Movie" },
  { trackName: "Night of the Living Dead", artworkUrl100: "https://image.tmdb.org/t/p/w500/5l0klDtj2v4FMFOGGCEH23AQb30.jpg", primaryGenreName: "Movie" },
  { trackName: "Lee Cronin's The Mummy", artworkUrl100: "https://image.tmdb.org/t/p/w500/1q308iixueCU4pFtSYugNOevtNx.jpg", primaryGenreName: "Movie" },
  { trackName: "Spider-Man: Brand New Day", artworkUrl100: "https://image.tmdb.org/t/p/w500/yyB2VJEW3an2xCdcYCPQhn9QERR.jpg", primaryGenreName: "Movie" },
  { trackName: "Kung Fu Soccer", artworkUrl100: "https://image.tmdb.org/t/p/w500/6QgJQrClh9ej357yzLWgCxrjAmJ.jpg", primaryGenreName: "Movie" },
  { trackName: "Black Box", artworkUrl100: "https://image.tmdb.org/t/p/w500/O7vJPEWsnLrKqPYHIHKG8zlEK1.jpg", primaryGenreName: "Movie" },
  { trackName: "Damage", artworkUrl100: "https://image.tmdb.org/t/p/w500/alf3JOPP7EYP0iO24gwe5YfRnqo.jpg", primaryGenreName: "Movie" },
  { trackName: "Minions & Monsters", artworkUrl100: "https://image.tmdb.org/t/p/w500/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg", primaryGenreName: "Movie" },
  { trackName: "We Want Now", artworkUrl100: "https://image.tmdb.org/t/p/w500/mQ95TSIl1QqNWCMQs1lTRgZUWT8.jpg", primaryGenreName: "Movie" },
  { trackName: "Shape of My Heart", artworkUrl100: "https://image.tmdb.org/t/p/w500/3r0O6BW9USoZ9mteCVyNKMQriRL.jpg", primaryGenreName: "Movie" },
  { trackName: "The Banished", artworkUrl100: "https://image.tmdb.org/t/p/w500/pBlTYknphiODxIQQrei030MSvdT.jpg", primaryGenreName: "Movie" },
  { trackName: "Demon Slayer: Infinity Castle", artworkUrl100: "https://image.tmdb.org/t/p/w500/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg", primaryGenreName: "Movie" },
  { trackName: "The Mandalorian and Grogu", artworkUrl100: "https://image.tmdb.org/t/p/w500/5Vi8dSauVwH1HOsiZceDMbRr1Ca.jpg", primaryGenreName: "Movie" },
  { trackName: "Graphic Desires", artworkUrl100: "https://image.tmdb.org/t/p/w500/3BjLdTWRiHc1ISIZMFvToOmghOM.jpg", primaryGenreName: "Movie" },
  { trackName: "Swapped", artworkUrl100: "https://image.tmdb.org/t/p/w500/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg", primaryGenreName: "Movie" },
  { trackName: "Kraken", artworkUrl100: "https://image.tmdb.org/t/p/w500/xdZ8k5s8DTwWyPBMIcflrYLgcAK.jpg", primaryGenreName: "Movie" },
  { trackName: "The Punisher: One Last Kill", artworkUrl100: "https://image.tmdb.org/t/p/w500/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg", primaryGenreName: "Movie" },
  { trackName: "Hoppers", artworkUrl100: "https://image.tmdb.org/t/p/w500/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg", primaryGenreName: "Movie" },
  { trackName: "Peddi", artworkUrl100: "https://image.tmdb.org/t/p/w500/wDoZa41ieE80WT5dQfC6QPC9Caf.jpg", primaryGenreName: "Movie" },
  { trackName: "The Sheep Detectives", artworkUrl100: "https://image.tmdb.org/t/p/w500/mGWOmj2jHFol3kOGNv1EhbSDDE1.jpg", primaryGenreName: "Movie" },
  { trackName: "Boulevard", artworkUrl100: "https://image.tmdb.org/t/p/w500/hAKOp4AHaDiVdDMlobMNCNgJVD7.jpg", primaryGenreName: "Movie" },
  { trackName: "Vixen!", artworkUrl100: "https://image.tmdb.org/t/p/w500/9KMZWDA3xTrlgrScqdMisINQmsh.jpg", primaryGenreName: "Movie" },
  { trackName: "Little Brother", artworkUrl100: "https://image.tmdb.org/t/p/w500/hIJpXb7Xaje2mebN9ylsS7blQzP.jpg", primaryGenreName: "Movie" },
  { trackName: "The Nurse on a Military Tour", artworkUrl100: "https://image.tmdb.org/t/p/w500/zvLqUjxh9RId7YzK8Xchu8fQaHk.jpg", primaryGenreName: "Movie" },
  { trackName: "Dolly", artworkUrl100: "https://image.tmdb.org/t/p/w500/sTPUg3XtdcKRAS5Vwsi1GYPFhNZ.jpg", primaryGenreName: "Movie" },
  { trackName: "Zombies of the Third Reich", artworkUrl100: "https://image.tmdb.org/t/p/w500/hjrgOWoruk9ea0tXaN8l2gtmkeH.jpg", primaryGenreName: "Movie" },
  { trackName: "I Know Who You Are", artworkUrl100: "https://image.tmdb.org/t/p/w500/dzS3PxisVd9y9BrLPiFfA2MvcI8.jpg", primaryGenreName: "Movie" },
  { trackName: "Summerween", artworkUrl100: "https://image.tmdb.org/t/p/w500/oCsyamu5ixofd3yyK9gD7pGfCiF.jpg", primaryGenreName: "Movie" },
  { trackName: "Satluj", artworkUrl100: "https://image.tmdb.org/t/p/w500/7ia3nAM4q9sBy8g3SVEVgRAcsKd.jpg", primaryGenreName: "Movie" },
  { trackName: "Apex", artworkUrl100: "https://image.tmdb.org/t/p/w500/eTp7gSPkSF3Aw79mNx1NkBP1PZT.jpg", primaryGenreName: "Movie" },
  { trackName: "Enola Holmes 3", artworkUrl100: "https://image.tmdb.org/t/p/w500/7kRYHH9H9PjBFwz1FprbHB2AAjI.jpg", primaryGenreName: "Movie" },
  { trackName: "The Shadow's Edge", artworkUrl100: "https://image.tmdb.org/t/p/w500/cHKo3m8N1fwvEy2ZEr0xGmmMODV.jpg", primaryGenreName: "Movie" },
  { trackName: "Raakaasa", artworkUrl100: "https://image.tmdb.org/t/p/w500/x7zwiuC1HTw5XGZ5JrOwF9uFqRy.jpg", primaryGenreName: "Movie" },
  { trackName: "Interstellar", artworkUrl100: "https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg", primaryGenreName: "Movie" },
  { trackName: "Simpsley", artworkUrl100: "https://image.tmdb.org/t/p/w500/qkJefER6Ym4v2KC1v4qK34AlcVo.jpg", primaryGenreName: "Movie" },
  { trackName: "Voicemails for Isabelle", artworkUrl100: "https://image.tmdb.org/t/p/w500/canZTWSxACSnAluir3dCtMxKpA1.jpg", primaryGenreName: "Movie" },
  { trackName: "In the Grey", artworkUrl100: "https://image.tmdb.org/t/p/w500/dQgIcW6Th08kMRf2HBoYWoFE6OD.jpg", primaryGenreName: "Movie" },
  { trackName: "Tom Clancy's Jack Ryan: Ghost War", artworkUrl100: "https://image.tmdb.org/t/p/w500/8ehYxUh5MWE41AeE9gkHE8DKzvB.jpg", primaryGenreName: "Movie" },
  { trackName: "Zootopia 2", artworkUrl100: "https://image.tmdb.org/t/p/w500/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg", primaryGenreName: "Movie" },
  { trackName: "Shelter", artworkUrl100: "https://image.tmdb.org/t/p/w500/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg", primaryGenreName: "Movie" },
  { trackName: "The Breadwinner", artworkUrl100: "https://image.tmdb.org/t/p/w500/4apG9Xk6HQvV48JKEjSUeiebju7.jpg", primaryGenreName: "Movie" },
  { trackName: "Au Bonheur des Dames", artworkUrl100: "https://image.tmdb.org/t/p/w500/lcshMRxDFWDtT2W9ImBeyuYnbg4.jpg", primaryGenreName: "Movie" },
  { trackName: "Inception", artworkUrl100: "https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg", primaryGenreName: "Movie" },
  { trackName: "GOAT", artworkUrl100: "https://image.tmdb.org/t/p/w500/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg", primaryGenreName: "Movie" },
  { trackName: "Spider-Man: No Way Home", artworkUrl100: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", primaryGenreName: "Movie" },
  { trackName: "Boulevard (Remake)", artworkUrl100: "https://image.tmdb.org/t/p/w500/sQS3zYJznspQwNSCv9LMc5VHQST.jpg", primaryGenreName: "Movie" },
  { trackName: "Moana 2", artworkUrl100: "https://image.tmdb.org/t/p/w500/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg", primaryGenreName: "Movie" },
  { trackName: "Lola's Secret", artworkUrl100: "https://image.tmdb.org/t/p/w500/qaJ4iQngrLbyz9OgaQkJLppDN6m.jpg", primaryGenreName: "Movie" },
  { trackName: "Send Help", artworkUrl100: "https://image.tmdb.org/t/p/w500/zbJWVHOtj3ljBzWgL1P8pxP03Up.jpg", primaryGenreName: "Movie" },
  { trackName: "Predator: Badlands", artworkUrl100: "https://image.tmdb.org/t/p/w500/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg", primaryGenreName: "Movie" },
  { trackName: "Seven Snipers", artworkUrl100: "https://image.tmdb.org/t/p/w500/pK6tGCG6UAgUT5FTq3ylGErHxQQ.jpg", primaryGenreName: "Movie" },
  { trackName: "The Housemaid", artworkUrl100: "https://image.tmdb.org/t/p/w500/cWsBscZzwu5brg9YjNkGewRUvJX.jpg", primaryGenreName: "Movie" },
  { trackName: "Avengers: Infinity War", artworkUrl100: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg", primaryGenreName: "Movie" },
  { trackName: "Poppea's Hot Nights", artworkUrl100: "https://image.tmdb.org/t/p/w500/g1kB4f7aZBJnU2XZILZ8TsyDVVM.jpg", primaryGenreName: "Movie" },
  { trackName: "Toy Story", artworkUrl100: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg", primaryGenreName: "Movie" },
  { trackName: "Ghost Stories", artworkUrl100: "https://image.tmdb.org/t/p/w500/m4ALMhsuqOOUkkABvgQWfrgoL8y.jpg", primaryGenreName: "Movie" },
  { trackName: "Bosco d'amore", artworkUrl100: "https://image.tmdb.org/t/p/w500/jNV46xSIONTEvIAWon6NnveH7eG.jpg", primaryGenreName: "Movie" },
  { trackName: "Your Fault: London", artworkUrl100: "https://image.tmdb.org/t/p/w500/nLxu237EJAisFCYKK48hN9Plobx.jpg", primaryGenreName: "Movie" },
  { trackName: "Ne Zha 2", artworkUrl100: "https://image.tmdb.org/t/p/w500/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg", primaryGenreName: "Movie" },
  { trackName: "My Fault", artworkUrl100: "https://image.tmdb.org/t/p/w500/w46Vw536HwNnEzOa7J24YH9DPRS.jpg", primaryGenreName: "Movie" },
  { trackName: "Toy Story 4", artworkUrl100: "https://image.tmdb.org/t/p/w500/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg", primaryGenreName: "Movie" },
  { trackName: "Dune", artworkUrl100: "https://image.tmdb.org/t/p/w500/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg", primaryGenreName: "Movie" },
  { trackName: "Shaolin Soccer", artworkUrl100: "https://image.tmdb.org/t/p/w500/z6ZQqwoxWy9muIxwUP4K2zWw7BU.jpg", primaryGenreName: "Movie" },
  { trackName: "Ikka", artworkUrl100: "https://image.tmdb.org/t/p/w500/fp5EAKE8nTx402n1fWz55QsuYY9.jpg", primaryGenreName: "Movie" },
  { trackName: "Greenland 2: Migration", artworkUrl100: "https://image.tmdb.org/t/p/w500/z2tqCJLsw6uEJ8nJV8BsQXGa3dr.jpg", primaryGenreName: "Movie" },
  { trackName: "The Dark Knight", artworkUrl100: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", primaryGenreName: "Movie" },
  { trackName: "The Intouchables", artworkUrl100: "https://image.tmdb.org/t/p/w500/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg", primaryGenreName: "Movie" },
  { trackName: "Infiltrate", artworkUrl100: "https://image.tmdb.org/t/p/w500/8Cw8GF9wG63kF8pRRXwOx2kXGt.jpg", primaryGenreName: "Movie" },
  { trackName: "The Matrix", artworkUrl100: "https://image.tmdb.org/t/p/w500/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg", primaryGenreName: "Movie" },
  { trackName: "Idhayam Murali", artworkUrl100: "https://image.tmdb.org/t/p/w500/iZzR7fYiJ3bGew8liRPxipPDEfj.jpg", primaryGenreName: "Movie" },
  { trackName: "Spirited Away", artworkUrl100: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", primaryGenreName: "Movie" },
  { trackName: "Evil Dead Rise", artworkUrl100: "https://image.tmdb.org/t/p/w500/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg", primaryGenreName: "Movie" },
  { trackName: "Crime 101", artworkUrl100: "https://image.tmdb.org/t/p/w500/tVvpFIoteRHNnoZMhdnwIVwJpCA.jpg", primaryGenreName: "Movie" },
  { trackName: "Supergirl", artworkUrl100: "https://image.tmdb.org/t/p/w500/moejGxR2haap29d9NQ7qe8x4eGj.jpg", primaryGenreName: "Movie" },
  { trackName: "Coraline", artworkUrl100: "https://image.tmdb.org/t/p/w500/4jeFXQYytChdZYE9JYO7Un87IlW.jpg", primaryGenreName: "Movie" },
  { trackName: "The Wild Robot", artworkUrl100: "https://image.tmdb.org/t/p/w500/eG9lz41mJqsI4J6ubMtVqD26q2J.jpg", primaryGenreName: "Movie" },
  { trackName: "Jurassic World Rebirth", artworkUrl100: "https://image.tmdb.org/t/p/w500/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg", primaryGenreName: "Movie" },
  { trackName: "Toy Story 2", artworkUrl100: "https://image.tmdb.org/t/p/w500/4rbcp3ng8n1MKHjpeqW0L7Fnpzz.jpg", primaryGenreName: "Movie" },
  { trackName: "Madness", artworkUrl100: "https://image.tmdb.org/t/p/w500/gV0J0Fqw2mYMtQbzb0ruxv9MAeZ.jpg", primaryGenreName: "Movie" }
];
